server:
  port: 8083

spring:
  application:
    name: ativos-service
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/orbita_ativos}
  data:
    mongodb:
      auto-index-creation: true
      representation:
        big-decimal: decimal128
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:orbita}
    password: ${RABBITMQ_PASSWORD:orbita}
    listener:
      simple:
        default-requeue-rejected: false

mensageria:
  exchange: orbita.eventos
  fila-de-consultas: ativos.consultas
  topicos:
    ativo-listado: ativo.listado
    ativo-atualizado: ativo.atualizado
    ativo-removido: ativo.removido
    cotacoes-atualizadas: ativo.cotacoes-atualizadas

orbita:
  dados-iniciais: ${ORBITA_DADOS_INICIAIS:true}
  cotacoes:
    intervalo-ms: 3000
