@startuml 04-casos-de-uso
title OrbitaPay — Casos de uso

skinparam shadowing false
skinparam defaultFontName "Segoe UI"
left to right direction

actor "Visitante" as vis
actor "Cliente" as cli
actor "Gerente" as ger
actor "Agendador\n(a cada 3 s)" as ag

vis <|-- cli

rectangle "OrbitaPay" {
  package "Clientes" {
    usecase "Cadastrar-se" as UC1
    usecase "Entrar com e-mail e PIN" as UC2
    usecase "Assinar operação com PIN" as UC3
    usecase "Alterar dados / PIN" as UC4
    usecase "Bloquear / desbloquear\na própria conta" as UC5
    usecase "Encerrar cadastro" as UC6
    usecase "Entrar como gerente" as UC7
    usecase "Gerir clientes\n(listar, editar, bloquear,\ndesbloquear, remover)" as UC8
  }
  package "Contas" {
    usecase "Consultar saldo e extrato" as UC10
    usecase "Depositar" as UC11
    usecase "Sacar" as UC12
    usecase "Listar contas" as UC13
  }
  package "Ativos" {
    usecase "Consultar ativos,\nbolsas e cotações" as UC20
    usecase "Listar / atualizar /\nremover ativo" as UC21
    usecase "Simular cotações" as UC22
  }
  package "Negociação" {
    usecase "Enviar ordem de compra" as UC30
    usecase "Enviar ordem de venda" as UC31
    usecase "Acompanhar ordens" as UC32
    usecase "Consultar oferta\ndisponível" as UC33
  }
  package "Carteira" {
    usecase "Consultar carteira" as UC40
    usecase "Consultar carteira\nde um cliente" as UC41
  }
}

vis --> UC1
vis --> UC20
vis --> UC33

cli --> UC2
cli --> UC4
cli --> UC5
cli --> UC6
cli --> UC10
cli --> UC11
cli --> UC12
cli --> UC30
cli --> UC31
cli --> UC32
cli --> UC40

ger --> UC7
ger --> UC8
ger --> UC13
ger --> UC21
ger --> UC41
ger --> UC1 : com depósito\ninicial

ag --> UC22

UC12 ..> UC3 : <<include>>
UC30 ..> UC3 : <<include>>
UC31 ..> UC3 : <<include>>
@enduml
